export default [
	{
		q: "Making money isn't hard in itself... What's hard is to earn it doing something worth devoting one's life to.",
		a: 'Carlos Ruiz Zafon',
		c: '108',
		h: "<blockquote>&ldquo;Making money isn't hard in itself... What's hard is to earn it doing something worth devoting one's life to.&rdquo; &mdash; <footer>Carlos Ruiz Zafon</footer></blockquote>",
	},
	{
		q: 'Hope is important because it can make the present moment less difficult to bear. If we believe that tomorrow will be better, we can bear a hardship today.',
		a: 'Thich Nhat Hanh',
		c: '154',
		h: '<blockquote>&ldquo;Hope is important because it can make the present moment less difficult to bear. If we believe that tomorrow will be better, we can bear a hardship today.&rdquo; &mdash; <footer>Thich Nhat Hanh</footer></blockquote>',
	},
	{
		q: 'The truth is simple. If it was complicated, everyone would understand it.',
		a: 'Walt Whitman',
		c: '73',
		h: '<blockquote>&ldquo;The truth is simple. If it was complicated, everyone would understand it.&rdquo; &mdash; <footer>Walt Whitman</footer></blockquote>',
	},
	{
		q: 'Being deeply loved by someone gives you strength, while loving someone deeply gives you courage. ',
		a: 'Lao Tzu',
		c: '97',
		h: '<blockquote>&ldquo;Being deeply loved by someone gives you strength, while loving someone deeply gives you courage. &rdquo; &mdash; <footer>Lao Tzu</footer></blockquote>',
	},
	{
		q: 'Success is about doing the right thing, not about doing everything right.',
		a: 'Gary Keller',
		c: '73',
		h: '<blockquote>&ldquo;Success is about doing the right thing, not about doing everything right.&rdquo; &mdash; <footer>Gary Keller</footer></blockquote>',
	},
	{
		q: 'Nothing can bring you peace but yourself.',
		a: 'Dale Carnegie',
		c: '41',
		h: '<blockquote>&ldquo;Nothing can bring you peace but yourself.&rdquo; &mdash; <footer>Dale Carnegie</footer></blockquote>',
	},
	{
		q: 'My definition of success is control.',
		a: 'Kenneth Branagh',
		c: '36',
		h: '<blockquote>&ldquo;My definition of success is control.&rdquo; &mdash; <footer>Kenneth Branagh</footer></blockquote>',
	},
	{
		q: 'Silence is sometimes the best answer',
		a: 'Dalai Lama',
		c: '36',
		h: '<blockquote>&ldquo;Silence is sometimes the best answer&rdquo; &mdash; <footer>Dalai Lama</footer></blockquote>',
	},
	{
		q: "Don't look for meaning in the words. Listen to the silences.",
		a: 'Samuel Beckett',
		c: '60',
		h: "<blockquote>&ldquo;Don't look for meaning in the words. Listen to the silences.&rdquo; &mdash; <footer>Samuel Beckett</footer></blockquote>",
	},
	{
		q: 'None of us can change our yesterdays but all of us can change our tomorrows.',
		a: 'Colin Powell',
		c: '76',
		h: '<blockquote>&ldquo;None of us can change our yesterdays but all of us can change our tomorrows.&rdquo; &mdash; <footer>Colin Powell</footer></blockquote>',
	},
	{
		q: 'There is nothing more frightful than ignorance in action.',
		a: 'Johann Wolfgang von Goethe',
		c: '57',
		h: '<blockquote>&ldquo;There is nothing more frightful than ignorance in action.&rdquo; &mdash; <footer>Johann Wolfgang von Goethe</footer></blockquote>',
	},
	{
		q: 'Those who dream by day are cognizant of many things which escape those who dream only by night.',
		a: 'Vincent van Gogh',
		c: '95',
		h: '<blockquote>&ldquo;Those who dream by day are cognizant of many things which escape those who dream only by night.&rdquo; &mdash; <footer>Vincent van Gogh</footer></blockquote>',
	},
	{
		q: 'Conquer the devils with a little thing called love.',
		a: 'Bob Marley',
		c: '51',
		h: '<blockquote>&ldquo;Conquer the devils with a little thing called love.&rdquo; &mdash; <footer>Bob Marley</footer></blockquote>',
	},
	{
		q: 'A mentor is someone who sees more talent and ability within you, than you see in yourself, and helps bring it out of you.',
		a: 'Bob Proctor',
		c: '121',
		h: '<blockquote>&ldquo;A mentor is someone who sees more talent and ability within you, than you see in yourself, and helps bring it out of you.&rdquo; &mdash; <footer>Bob Proctor</footer></blockquote>',
	},
	{
		q: 'Unless a man is master of his soul, all other kinds of mastery amount to little.',
		a: 'Theodore Roosevelt',
		c: '80',
		h: '<blockquote>&ldquo;Unless a man is master of his soul, all other kinds of mastery amount to little.&rdquo; &mdash; <footer>Theodore Roosevelt</footer></blockquote>',
	},
	{
		q: 'Sometimes your joy is the source of your smile, but sometimes your smile can be the source of your joy.',
		a: 'Thich Nhat Hanh',
		c: '103',
		h: '<blockquote>&ldquo;Sometimes your joy is the source of your smile, but sometimes your smile can be the source of your joy.&rdquo; &mdash; <footer>Thich Nhat Hanh</footer></blockquote>',
	},
	{
		q: 'It matters not who you love, where you love, why you love, when you love or how you love, it matters only that you love.',
		a: 'John Lennon',
		c: '120',
		h: '<blockquote>&ldquo;It matters not who you love, where you love, why you love, when you love or how you love, it matters only that you love.&rdquo; &mdash; <footer>John Lennon</footer></blockquote>',
	},
	{
		q: 'Do not dwell in the past, do not dream of the future, concentrate the mind on the present moment.',
		a: 'Buddha',
		c: '97',
		h: '<blockquote>&ldquo;Do not dwell in the past, do not dream of the future, concentrate the mind on the present moment.&rdquo; &mdash; <footer>Buddha</footer></blockquote>',
	},
	{
		q: "One always begins to forgive a place as soon as it's left behind.",
		a: 'Charles Dickens',
		c: '65',
		h: "<blockquote>&ldquo;One always begins to forgive a place as soon as it's left behind.&rdquo; &mdash; <footer>Charles Dickens</footer></blockquote>",
	},
	{
		q: "It doesn't matter where you are coming from. All that matters is where you are going. ",
		a: 'Brian Tracy',
		c: '86',
		h: "<blockquote>&ldquo;It doesn't matter where you are coming from. All that matters is where you are going. &rdquo; &mdash; <footer>Brian Tracy</footer></blockquote>",
	},
]